apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: workshop
  labels: { app: api }
spec:
  replicas: 2
  selector: { matchLabels: { app: api } }
  template:
    metadata:
      labels: { app: api }
    spec:
      containers:
        - name: api
          image: kennethreitz/httpbin
          ports: [{ name: http, containerPort: 80 }]
          # Ressources -> QoS "Burstable"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
          readinessProbe:
            httpGet: { path: /status/200, port: http }
            initialDelaySeconds: 5
            periodSeconds: 5
