apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotrod
  namespace: observability
  labels: { app: hotrod }
spec:
  replicas: 1
  selector: { matchLabels: { app: hotrod } }
  template:
    metadata: { labels: { app: hotrod } }
    spec:
      containers:
      - name: hotrod
        image: jaegertracing/example-hotrod:1.57
        ports: [{ containerPort: 8080, name: http }]
        env:
        - name: JAEGER_ENDPOINT
          value: http://simplest-collector.observability.svc:14268/api/traces
        - name: JAEGER_DISABLED
          value: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: hotrod
  namespace: observability
spec:
  selector: { app: hotrod }
  ports: [{ name: http, port: 8080, targetPort: http, protocol: TCP }]
