apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: observability
  namespace: observability
  annotations:
    cert-manager.io/cluster-issuer: selfsigned
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - grafana.local
    - prometheus.local
    - alertmanager.local
    - jaeger.local
    secretName: obs-tls
  rules:
  - host: grafana.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            # nom du service grafana du chart kube-prometheus-stack
            name: monitor-grafana
            port:
              number: 80
  - host: prometheus.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            # prom du chart (adapte si ton nom diffère)
            name: monitor-kube-prometheus-stack-prometheus
            port:
              number: 9090
  - host: alertmanager.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            # alertmanager du chart
            name: monitor-kube-prometheus-stack-alertmanager
            port:
              number: 9093
  - host: jaeger.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            # si tu as déployé Jaeger "simplest" (operator ou standalone)
            name: simplest-query
            port:
              number: 16686
